### ISSUE TITLE
语义分割的问题

### ISSUE THREAD

**Issue by LZQ1204** [AnTao97/dgcnn.pytorch#55]
您好，我在复现语义分割的时候，成功生成了需要的文件夹，但是最后还是出现了如下问题：

Stored /home/ipsg/code/lzq/partseg/dgcnn.pytorch-master/data/indoor3d_sem_seg_hdf5_data_test/ply_data_all_7.h5 with size 602
Total samples: 7602
Traceback (most recent call last):
  File "main_semseg.py", line 429, in <module>
    train(args, io)
  File "main_semseg.py", line 151, in train
    train_loader = DataLoader(S3DIS(partition='train', num_points=args.num_points, test_area=args.test_area), 
  File "/home/ipsg/code/lzq/partseg/dgcnn.pytorch-master/data.py", line 337, in __init__
    self.data, self.seg = load_data_semseg(partition, test_area)
  File "/home/ipsg/code/lzq/partseg/dgcnn.pytorch-master/data.py", line 152, in load_data_semseg
    test_area_name = "Area_" + test_area
TypeError: can only concatenate str (not "NoneType") to str

**Comment by antao97** [comment]
你没有写`--test_area`，请按照README中提供的范例运行代码
