### ISSUE TITLE
作者您好，请问是否可以看一下您在ScanNet数据集中的data目录？

### ISSUE THREAD

**Issue by xiaoyangyang123** [AnTao97/dgcnn.pytorch#80]

**Comment by antao97** [comment]
`data/ScanNet/`文件夹下有`scans/`和`scans_test/`

**Comment by xiaoyangyang123** [comment]
好的，谢谢~

**Comment by xiaoyangyang123** [comment]
**** Epoch 0 (0/200) ****
BN momentum updated to: 0.1000
Traceback (most recent call last):
  File "main_semseg_scannet.py", line 602, in <module>
    train(args, io)
  File "main_semseg_scannet.py", line 225, in train
    for i, data in tqdm(enumerate(train_loader),
  File "C:\Users\admin\Anaconda3\envs\point\lib\site-packages\torch\utils\data\dataloa
der.py", line 368, in __iter__
    return self._get_iterator()
  File "C:\Users\admin\Anaconda3\envs\point\lib\site-packages\torch\utils\data\dataloa
der.py", line 314, in _get_iterator
    return _MultiProcessingDataLoaderIter(self)
  File "C:\Users\admin\Anaconda3\envs\point\lib\site-packages\torch\utils\data\dataloa
der.py", line 927, in __init__
    w.start()
    reduction.dump(process_obj, to_child)
  File "C:\Users\admin\Anaconda3\envs\point\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
AttributeError: Can't pickle local object 'train.<locals>.<lambda>'

你好，我运行主函数的时候，出现了该错误，请问您有遇到同样的错误吗？我有百度解决办法，但是都未成功。

**Comment by xiaoyangyang123** [comment]
安涛你好，我在进行model的val时，他总是卡在Room 231/312, mIoU 0.2763，您知道这是为什么吗？我运行您的model结果也是同样的情况。
